export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_EXISTING = 'LOGIN_EXISTING'
export const LOGOUT_REQUESTING = 'LOGOUT_REQUESTING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'


export const CLIENT_SET = 'CLIENT_SET'
export const CLIENT_UNSET = 'CLIENT_UNSET'

export const FETCH_CHAR_SUCCESS = 'FETCH_CHAR_SUCCESS'
export const FETCH_CHAR_REQUESTING = 'FETCH_CHAR_REQUESTING'
export const FETCH_CHAR_ERROR = 'LOGIN_ERROR'
export const SEARCH_CHAR = 'SEARCH_CHAR'
